r2p2_sea_arm_right:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  right_arm_shoulder_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_arm_shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_shoulder_pitch_shoulder_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_shoulder_pitch_shoulder_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_shoulder_yaw_upper_arm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_shoulder_yaw_upper_arm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_upper_arm_elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_upper_arm_elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
