#
# Open Source Android - configuration file
#
# Parameters:
#
# dofX has CAN node ID X
#
# type:
#    TENDON
#    CLASSICAL
#    SEA
#    WHEEL
#
# controller:
#    NOT_USED
#    EPOS2
#    EPOS4
#
# motor:
#    NONE
#    DCX10
#    DCX12
#    DCX14
#    DCX16
#    DCX22
#    DCX32
#    RE13
#    RE30
#    ECI30
#    ECI40
#    ECI52
#    EC32F_12
#    EC32F_24
#    EC90
#
# inverted:
#    false
#    true
#
# mode: mode of operation selected during initialization: 
#    INTERPOLATED_POSITION_MODE
#    PROFILE_VELOCITY_MODE
#    PROFILE_POSITION_MODE
#    POSITION_MODE
#    VELOCITY_MODE
#    CURRENT_MODE
#    CYCLIC_SYNCHRONOUS_TORQUE_MODE
#
# value: default value that will be sent after EPOS board initialization, according to the selected mode of operation
# 

robot:
  name: 'r2p_sea_arm'
  dof: 9  # Number of Degrees Of Freedom.
  can_device: 'can1'
  heartbeat: 50

# Base
dof1: {name: 'arm/right/shoulder/pitch', type: 'SEA', node_id: 1, controller: 'EPOS4', motor: 'ECI30', inverted: false, mode: 'PROFILE_POSITION_MODE', value: 0}
dof2: {name: 'arm/right/shoulder/yaw', type: 'SEA', node_id: 2, controller: 'EPOS2', motor: 'EC32F_12', inverted: true, mode: 'CURRENT_MODE', value: 0}
dof3: {name: 'arm/right/shoulder/humerus', type: 'SEA', node_id: 3, controller: 'EPOS2', motor: 'EC32F_12', inverted: false, mode: 'CURRENT_MODE', value: 0}
dof4: {name: 'arm/right/elbow', type: 'SEA', node_id: 4, controller: 'EPOS2', motor: 'EC32F_12', inverted: false, mode: 'CURRENT_MODE', value: 0}
dof5: {name: 'arm/right/hand', type: 'TENDON', node_id: 5, controller: 'EPOS2', motor: 'RE25', inverted: false, mode: 'CURRENT_MODE', value: 150}

dof6: {name: 'arm/left/shoulder/pitch', type: 'SEA', node_id: 6, controller: 'EPOS4', motor: 'ECI30', inverted: true, mode: 'PROFILE_POSITION_MODE', value: 0}
dof7: {name: 'arm/left/shoulder/yaw', type: 'SEA', node_id: 7, controller: 'EPOS4', motor: 'EC32F_12', inverted: false, mode: 'PROFILE_POSITION_MODE', value: 0}
dof8: {name: 'arm/left/shoulder/humerus', type: 'SEA', node_id: 8, controller: 'EPOS4', motor: 'EC32F_12', inverted: true, mode: 'PROFILE_POSITION_MODE', value: 0}
dof9: {name: 'arm/left/elbow', type: 'SEA', node_id: 9, controller: 'EPOS4', motor: 'EC32F_12', inverted: true, mode: 'PROFILE_POSITION_MODE', value: 0}
#dof5: {name: 'arm/hand', type: 'TENDON', node_id: 5, controller: 'EPOS4', motor: 'RE25', inverted: false, mode: 'CURRENT_MODE', value: 150}

